sudo: false
language: node_js
node_js:
  - stable
script:
  - yarn build-all
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: m4nfaDFDuIrL1EBWb8dUCijzCRKBK8cuMwNzmm74KSmv62RCoscZW6MX3wAhyEE4Rq1kL7hZYni0GKxtl2ntl7ztStCU/Vfc6eTQrQNkZfrjqoXmk1JGBZnrlndpIvXkXN0TWEpPmofxKiTP5gc+vL4OjhaYRK01XqhXZEGVjqqkBKfoalmB/6ToBDOwMEoJcn9ot+sU/Cbii8bXG1GZ0zkZzL69R57mAhpbzt3y85eeflucfUVfGtI/apkIrCEqrzOjP0UxUVObmXPVyhJGXwmd5GUE2y7Q7/TeQ7DLZlb415k8P6vTCNrCbCUY/dxin/tUhvueI3TXtJYr3oNApiLorFjpIyUyvwJJjy/DVcym4BcA197px8zvNjnkTYjFdbIyo6lZ3n0lvhjcAf83uzLGSfrCmfeqvwk1gF/Ljfrom4dJMai4ul/MlXynK/LLnc/O+zC1P8n+8a629h+nYFdGIiNDQFIwV5+rB/ahb2tsC4gDUUKcqk2+a7ujA6c2Z86JPVu0S5TzG2k+QB21NZ9m+nGLdOlEzOSA9fp0KbU4XZiqn5ijpygAp33dMHLTeqFdDTxlSVgFEL3dYkr4CH3DY3vqPjR9J8VhbktzMBxKROSChNXmWJFluOXXOdf5b6cKcboWvYcI3cUer/TGy2E3I1ypSGTZeeol/L3+O8M=
